version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: ephraimapps-mongodb_web_1
      APP_PORT: 8083

  # ----------------------------------------------------------
  # Main MongoDB server (7.x for local vector indexing)
  # ----------------------------------------------------------
  mongo:
    image: mongo:7.0.0
    user: "1000:1000"
    init: true
    restart: on-failure
    stop_grace_period: 1m

    environment:
      MONGO_INITDB_ROOT_USERNAME: "umbrel"
      MONGO_INITDB_ROOT_PASSWORD: "secretpassword"

    volumes:
      - ${APP_DATA_DIR}/data:/data/mongodb

  # ----------------------------------------------------------
  # Mongo Express (web-based Mongo admin UI)
  # ----------------------------------------------------------
  web:
    image: mongo-express:latest
    user: "1000:1000"
    init: true
    restart: on-failure
    stop_grace_period: 1m

    environment:
      # Point to the "mongo" service above
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ADMINUSERNAME: umbrel
      ME_CONFIG_MONGODB_ADMINPASSWORD: secretpassword
      # The internal port on which Mongo Express listens
      ME_CONFIG_SITE_PORT: 8083

