version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: ephraimapps-wordwall_web_1
      APP_PORT: 9287

  web:
    image: johnygabriel/word-wall-game:latest
    container_name: ephraimapps-wordwall_web_1 
    restart: on-failure
    stop_grace_period: 1m
    
    volumes:
      - ${APP_DATA_DIR}/data:/app/data

    environment:
      NODE_ENV: production
      PORT: 9287

    command: ["npm", "start"]