# Omit or remove the version line to avoid Umbrel's “obsolete” warnings.
# version: "3.7"

services:
  # ------------------------------------------------------
  # 1) Umbrel proxy
  # ------------------------------------------------------
  app_proxy:
    environment:
      # Must match <app-id>_<service-name>_1
      # If your app ID is "ephraimapps-surrealdb" and your service is "server",
      # this container will be "ephraimapps-surrealdb_server_1".
      APP_HOST: ephraimapps-surrealdb_server_1
      # SurrealDB listens by default on 8000 (HTTP).
      APP_PORT: 8000

  # ------------------------------------------------------
  # 2) SurrealDB server
  # ------------------------------------------------------
  server:
    image: surrealdb/surrealdb:latest

    # If you have permission errors on Umbrel, consider removing or adjusting this line
    # user: "1000:1000"

    # Ensure SurrealDB restarts on failure
    restart: on-failure
    stop_grace_period: 1m
    init: true

    # SurrealDB "start" command example:
    #  - Binds to "0.0.0.0:8000" so it can accept connections within Docker
    #  - "file:///data" ensures SurrealDB stores data in /data
    command:
      [
        "start",
        "--bind",
        "0.0.0.0:8000",
        "--user",
        "umbrel",
        "--pass",
        "secretpassword",
        "--log",
        "debug",
        "file:///data"
      ]

    volumes:
      # Map Umbrel's persistent data dir to /data in the container
      - ${APP_DATA_DIR}/data:/data
