manifestVersion: 1
id: surrealdb
category: development
name: SurrealDB
version: "2.1.4"
tagline: "A scalable and fast database for the cloud, serverless environments, and the edge."
description: "SurrealDB is a multi-model database built for modern applications, offering document, graph, and key-value storage in one system."
releaseNotes: "Initial release of SurrealDB integration with UmbrelOS."
developer: "SurrealDB Team"
website: "https://surrealdb.com"
repository: "https://github.com/surrealdb/surrealdb"
support: "https://github.com/surrealdb/surrealdb/issues"
path: ""
ports:
  - 8000
icon: "https://surrealdb.com/favicon.ico"
gallery:
  - "https://surrealdb.com/assets/img/showcase-1.png"
  - "https://surrealdb.com/assets/img/showcase-2.png"
  - "https://surrealdb.com/assets/img/showcase-3.png"
dependencies: []
minUmbrelVersion: "0.5.0"
hiddenService: true
defaultPassword: "${APP_PASSWORD}"
