version: "3.7"

services:
  app_proxy:
    image: getumbrel/umbrel-app-proxy:latest
    environment:
      APP_HOST: surrealdb
      APP_PORT: 8000

  surrealdb:
    image: surrealdb/surrealdb:latest
    restart: unless-stopped
    command: ["start", "--user", "root", "--pass", "${APP_PASSWORD}"]
    environment:
      SURREAL_LOG: info
    volumes:
      - ${APP_DATA_DIR}/data:/data
    expose:
      - "8000"
