version: "3.7"

x-environment: &mongo_env
  MONGO_INITDB_ROOT_USERNAME: "umbrel"
  MONGO_INITDB_ROOT_PASSWORD: "secretpassword"

services:
  app_proxy:
    environment:
      APP_HOST: ephraimapps-mongodb_mongo-express_1
      APP_PORT: 8084

  mongo:
    image: mongo:7.0.0
    restart: on-failure
    ports:
      - "27017:27017"
    command: ["--bind_ip_all"]
    environment:
      <<: *mongo_env
    volumes:
      - ${APP_DATA_DIR}/data:/data/db

  mongo-express:
    image: mongo-express:latest
    restart: on-failure
    # Remove the ports mapping since app_proxy handles external access
    depends_on:
      - mongo
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ADMINUSERNAME: "umbrel"
      ME_CONFIG_MONGODB_ADMINPASSWORD: "secretpassword"
      ME_CONFIG_SITE_PORT: 8084