services:
  # ------------------------------------------------------
  # 1) Umbrel Proxy
  # ------------------------------------------------------
  app_proxy:
    environment:
      # This must match the app ID and service name
      APP_HOST: ephraimapps-surrealdb_server_1
      # SurrealDB's default HTTP port is 8000, but we're using 7892
      APP_PORT: 7892

  # ------------------------------------------------------
  # 2) SurrealDB Server
  # ------------------------------------------------------
  server:
    image: surrealdb/surrealdb:latest
    container_name: surrealdb_server
    restart: unless-stopped
    stop_grace_period: 1m
    init: true

    # SurrealDB "start" command
    command:
      [
        "start",
        "--bind",
        "0.0.0.0:7892",
        "--user",
        "umbrel",
        "--pass",
        "secretpassword",
        "--log",
        "debug",
        "file:///data"
      ]

    # Persistent storage for database
    volumes:
      - ${APP_DATA_DIR}/data:/data


    # Environment Variables (Optional)
    environment:
      SURREALDB_USER: "umbrel"
      SURREALDB_PASS: "secretpassword"

    networks:
      - surrealdb_net

networks:
  surrealdb_net:
    driver: bridge
