version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: ephraimapps-surrealdb_web_1
      APP_PORT: 8000

  web:
    image: surrealdb/surrealdb:1.0.0
    restart: on-failure
    stop_grace_period: 1m
    command: start --user $SURREAL_USER --pass $SURREAL_PASS file:/data/surreal.db
    environment:
      SURREAL_USER: root
      SURREAL_PASS: root
      SURREAL_BIND: 0.0.0.0:8000

    volumes:
      - ${APP_DATA_DIR}/data:/data

    healthcheck:
      test: ["CMD", "surreal", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3