version: "3.7"

services:

  app_proxy:
    environment:
      # Format: <app-id>_<docker-service-name>_1
      APP_HOST: mongodb_mongo-express_1
      APP_PORT: 8082

  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - mongodb_data:/data/db
    networks:
      - mongo_network

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: unless-stopped
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_MONGODB_URL: mongodb://admin:password@mongodb:27017/
    ports:
      - "8082:8082"
    networks:
      - mongo_network

networks:
  mongo_network:
    driver: bridge

volumes:
  mongodb_data:
